quarkus.datasource.db-kind=mariadb
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.hibernate-orm.database.generation=update

quarkus.http.cors=true
# Autoriser l'origine du frontend
quarkus.http.cors.origins=http://localhost:4200
# Méthodes HTTP autorisées
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
# Autoriser les en-têtes spécifiques si nécessaires
quarkus.http.cors.headers=Content-Type,Authorization
# Permettre l'envoi des cookies ou des identifiants (si nécessaire)
quarkus.http.cors.access-control-allow-credentials=true
